spring.application.name=ordemServico

spring.datasource.url=jdbc:mysql://172.16.0.30:3306/bdsj_osapi?createDatabaseIfNotExist=true&serverTimezone=UTC 

spring.datasource.username=bdsj
spring.datasource.password=gmSenai

spring.jpa.show-sql=True